name: Publish Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'placeholder'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build site
        run: yarn build
        env:
          VECTO_PUBLIC_TOKEN: ${{ secrets.VECTO_PUBLIC_TOKEN }}
          VECTO_USER_TOKEN: ${{ secrets.VECTO_USER_TOKEN }}
          VECTO_SPACE_ID: ${{ secrets.VECTO_SPACE_ID }}

      - name: Copying to xircuits.io
        run: rsync -a -v -h build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/xircuits.io/ --delete
