name: Validate Build

on:
  workflow_dispatch:
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Build Env
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install 18.14.2
          nvm use 18.14.2


      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run-script build
        env:
          VECTO_PUBLIC_TOKEN: ${{ secrets.VECTO_PUBLIC_TOKEN }}
          VECTO_USER_TOKEN: ${{ secrets.VECTO_USER_TOKEN }}
          VECTOR_SPACE_ID: ${{ secrets.VECTOR_SPACE_ID }}
